[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NODE_VERSION = "20"

# Redirect /admin to /admin/ for Decap CMS
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Ensure trailing slashes for existing pages only
[[redirects]]
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false
  conditions = {Status = [200]}

# 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

